//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShakkiProjekti.ShakkiService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ShakkiService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Tallennus", ReplyAction="http://tempuri.org/IService1/TallennusResponse")]
        string Tallennus(string ValkoinenNimimerkki, string MustaNimimerkki, int Vuorot, string Voittaja);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Tallennus", ReplyAction="http://tempuri.org/IService1/TallennusResponse")]
        System.Threading.Tasks.Task<string> TallennusAsync(string ValkoinenNimimerkki, string MustaNimimerkki, int Vuorot, string Voittaja);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ShakkiProjekti.ShakkiService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ShakkiProjekti.ShakkiService.IService1>, ShakkiProjekti.ShakkiService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Tallennus(string ValkoinenNimimerkki, string MustaNimimerkki, int Vuorot, string Voittaja) {
            return base.Channel.Tallennus(ValkoinenNimimerkki, MustaNimimerkki, Vuorot, Voittaja);
        }
        
        public System.Threading.Tasks.Task<string> TallennusAsync(string ValkoinenNimimerkki, string MustaNimimerkki, int Vuorot, string Voittaja) {
            return base.Channel.TallennusAsync(ValkoinenNimimerkki, MustaNimimerkki, Vuorot, Voittaja);
        }
    }
}
